import type { Metadata } from "next";

import "@/styles/globals.css";
import { AppProps } from "next/app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import DefaultLayout from "@/components/layout/DefaultLayout";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useAuth } from "@/store/auth";
import AppLayout from "@/components/layout/AppLayout";

export default function RootLayout({ Component, pageProps }: AppProps) {
  const router = useRouter();
  const auth = useAuth();
  
  useEffect(() => {
    (async () => {
      let token = localStorage.getItem("token");
      if (!token) return auth.setLoading(false);

      try {
        let res = await fetch("/api/auth/me", {
          headers: {
            Authorization: token
          }
        });

        let json = await res.json();

        if (!json?.success) throw Error(json?.message || "Unknown error!");

        auth.setUser(json.user);
        auth.setLoading(false);
      } catch (error) {
        auth.setLoading(false);
        localStorage.removeItem("token");
      }
    })();
  }, []);

  const children = <Component {...pageProps} />;

  return (
    <>
      {
        router.pathname.includes("/app") ? (
          <AppLayout>
            {children}
          </AppLayout>
        ) : (
          <DefaultLayout>
            {children}
          </DefaultLayout>
        )
      }
    </>
  );
}
